julia-vscode/LanguageServer.jl

- .travis.yml
They seem to be continually stuck, and I don't really think we have any mac specific things. I'd say we can reenable before we release a version, but for now those builds just seem to slow things down.
> Disable mac builds on travis

- src/cache.jl
- src/languageserverinstance.jl
- src/provider_completions.jl
- src/provider_misc.jl
- src/utilities.jl
This loads a child process for build the cache for `Main` and any references mods. There's some sort of conflict between the user's package directory and the LS one but  I can't quite pin down the problem yet.
I still want to get the `Base` caching faster so I'm going to look into transferring it submodule by submodule rather than as a single object
> WIP: Load cache in spawned process

- src/cache.jl
- src/provider_misc.jl
``server.user_pkg_dir`` actually points to ``.julia/v0.5``, but we need ``JULIA_PKGDIR`` to point to ``.julia``. This should fix things.
> Fix path used for client process

- src/protocol.jl
`JSON._writejson` was an internal implementation detail and should not have been used to override the serialization of `Range`. In JSON 0.9.0, `_writejson` has been removed.
cc @tkelman, see https://github.com/JuliaLang/METADATA.jl/pull/8820#issuecomment-294069652
> Use JSON.lower specialization

- src/protocol/configuration.jl
Add constructor when client provides an empty `workspace`
To support existing logic at [protocol/configuration.jl#L128](https://github.com/joshbode/LanguageServer.jl/blob/73865dad7a1c2d273266ae32c07bba9e9bcbbfdb/src/protocol/configuration.jl#L128).
> WorkspaceClientCapabilities constructor for empty capabilities

- src/provider_misc.jl
- test/test_communication.jl
This should fix [this](https://github.com/JuliaEditorSupport/julia-vscode/issues/188), and incremental text update is not needed until incremental parsing returns
> transfer full doc text on change

- src/provider_diagnostics.jl
- test/test_lint.jl
Re-implements `Julia: Toggle Linter` command to switch on/off diagnostics (and thus formatting also)
> re-implement linter toggle

- src/lint.jl
- src/scope.jl
This fixes the names of symbols defined within nested modules (noticed [here](https://github.com/ZacLN/CSTParser.jl/issues/18))
> fix symbols names in nested modules

- src/trav/lint.jl
Checks for exporting of undefined variables, moves check of duplicated exports from CSTParser to LanguageServer
> lint exports

- src/trav/lint.jl
- test/test_lint.jl
Adds check for defining an abstract with an already defined name, moves deprecated syntax check from CSTParser to LanguageServer
> abstract linting

- src/trav/lint.jl
Adds more linting of type definitions, moves stuff from CSTParser to LanguageServer
Note: though this passes tests it won't work properly without an up to date version of `CSTParser`
> Lint types

- src/provider_action.jl
- src/provider_completions.jl
- src/provider_definitions.jl
- src/provider_formatting.jl
- src/provider_hover.jl
- src/provider_links.jl
- src/provider_references.jl
- src/provider_signatures.jl
- src/provider_symbols.jl
Return empty response if `uri` in provider request can't be found
> return cancel response on unknown uri request

- src/trav/lint.jl
fix symbol lookup (convert identifier to string) and duplicated variable names inside modules
> fix duplicate name confusion with modules

- src/trav/lint.jl
previously was comparing `EXPR{IDENTIFIER}` w/ string
> fix inner constructor name check

- src/languageserverinstance.jl
Fixes segfaults reported https://github.com/JuliaEditorSupport/julia-vscode/issues/236.
Sorry @davidanthoff, one more fix. Though I don't think this needs a new RC release: it's a one line change cutting out crashes!
> don't import `:.`

- src/trav/toplevel.jl
This fixes #185 on my system.
I don't think we need to redirect ``STDERR`` here, that is not used for the language server communication in any case.
We already redirect ``STDOUT`` [here](https://github.com/JuliaEditorSupport/julia-vscode/blob/master/scripts/languageserver/main.jl#L10), and I think that should be enough to prevent problems in the communication between the LS and vscode.
> Fix STDERR redirection error

- src/trav/local.jl
removes assumption that anon. function args are no type declared
> fix local variable assignment in anonymous functions

- src/utilities.jl
I think we should treat things as case sensitive on Windows, not like I did so far. That seems to be more in line with NTSF. This seems to at least move us in the right direction with respect to the path problems on Windows, not all the way yet, though...
> Remove lowercase calls for win paths

- src/provider_definitions.jl
- src/provider_diagnostics.jl
- src/provider_misc.jl
- src/provider_references.jl
- src/trav/lint.jl
- src/trav/local.jl
- src/trav/toplevel.jl
- src/utilities.jl
This a) fixes ``filepath2uri`` on win and b) uses that function in various places where I think it should be used.
I also added a ``joinuriwithpath`` function that does that correctly on Windows and use that where it should be used.
> Various filepath2uri fixes

- contrib/languageserver.sh
This is a script which I use in Sublime Text #166  to launch LanguageServer.
The reason of this is because Julia spawns a child process while precompiling packages and that childprocess makes julia so resistant so that julia won't be killed even the editor exits which leaves a orphan julia process. This script detects if the julia process is orphan and kill it and its possible child processes.
This script could be also used in other editors, e.g., emacs/neovim. Or even VSCode, not sure if VSCode is smart enough to kill all child processes.
It should also work on linux, though, I have only tested it on macOS. Also, not sure if Windows suffers from the same issue.
> script to launch LanguageServer

- src/protocol/configuration.jl
- src/provider_misc.jl
- test/test_communication.jl
This is how I interpret the [spec](https://github.com/Microsoft/vscode-languageserver-node/blob/master/protocol/src/protocol.workspaceFolders.proposed.md) and what we should do. But for some reason that also doesn't seem enough to trigger the workspace change notifications. I'm waiting for some feedback on the VS Code slack right now, but maybe we can merge this in the meantime, it does seem slightly more in line with the spec than the previous iteration?
> Use correct server capabilities form

- src/languageserverinstance.jl
- src/provider_misc.jl
- src/utilities.jl
I think we should just entirely remove the ``rootPath`` field from our internal design. Even when we have a client that doesn't support multi root, we can just handle that as a multi-root situation with only one entry in ``workspaceFolders``.
@ZacLN This PR would merge things into the branch ``wkspflds``. I might have another PR coming in the same manner. Once we have everything sorted out on ``wkspflds``, we can then merge it into ``master``.
> Remove rootPath from LS

- REQUIRE
- src/languageserverinstance.jl
- src/provider_completions.jl
- src/provider_definitions.jl
- src/provider_hover.jl
- src/provider_references.jl
- src/provider_signatures.jl
- src/trav/lint.jl
- src/trav/local.jl
- src/trav/toplevel.jl
Updates for changes to CSTParser interface
> update for cstparser changes

- src/requests/textDocument.jl
prevents us from attempting to access a string in the middle of a unicode character
> string access fix

- src/languageserverinstance.jl
I was having issues precompiling and using the LS since it was complaining about SymbolServer not being found. This fixes the error for me.
> Fixed loading SymbolServer, as referenced in issue 300

- Project.toml
@ZacLN These are good for the current `master` branch. I think you should probably then merge `master` into https://github.com/julia-vscode/LanguageServer.jl/pull/350, and then adjust those bounds in that PR for the packages that you need there.
> Use semver compat bounds

- src/utilities.jl
1.1 doesn't have it, I think 1.2 is the first to come with it.
> Fix version check for _splitdir_nodrive

- src/utilities.jl
For some reason `path_dir_splitter` is not defined on julia 1.1.1.
For now I just copied it, that seems an easy fix.
> Fix bug related to path_dir_splitter

- src/protocol/configuration.jl
`documentChanges` can be null according to specs. This is needed for other lsp clients, like [lsp4intellij](https://github.com/ballerina-platform/lsp4intellij)
> documentChanges is nullable

- contrib/languageserver.sh
STDIN and STDOUT are lowercase now, and you get "ERROR: Couldn't load core stores" (see https://github.com/julia-vscode/LanguageServer.jl/issues/375) without SymbolServer.
> Update languageserver.sh to support Julia 1.0

- src/utilities.jl
Fixes #393. Current approach is obviously incorrect as it calls a constructor method that doesn't exist since https://github.com/JuliaLang/Tokenize.jl/pull/151.
> Use new RawToken constructor

- src/requests/textdocument.jl
- test/runtests.jl
- test/test_document.jl
Closes #403
The problem is that `Document._line_offsets` isn't updated until all changes from a particular rpc message have been processed. I think this bug hasn't been seen before because `textDocument/didChange` with multiple changes are rare in practice. There may be a more performant way of updating the offsets for each change, but this should at least fix the problem.
> Force recalc of line offsets for each document change

- src/document.jl
- src/languageserverinstance.jl
- src/parsing.jl
- src/requests/init.jl
- src/requests/textdocument.jl
- src/requests/workspace.jl
This now always runs the linter, the only thing one can control is whether the messages are actually published to the client. The setting now also works again :)
Now generally fixes how configuration changes are handled, also for format options.
The second linter setting (the ignore list) was not hooked up in any case, so I just removed that.
> Fix configuration handling

- src/protocol/configuration.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/pull/416.
@non-Jedi does this work now for you?
> Fix a bug how missing values in ConfigurationItem are handled

- src/requests/init.jl
This just rearranges the checks so that it first checks whether the folder exists and there are read permissions, before it calls `isjuliabasedir` (which will crash if the folder doesn't exist.
This should fix a big that came in via crash reporting.
> Fix load_rootpath

- src/requests/hover.jl
- test/test_hover.jl
Markedstring is deprecated, this moves us to using MarkupContent for hovers. This removes the need for manual handling of code blocks for SymbolServer documentation (#364).
> use MarkupContent for Hovers

- src/requests/features.jl
running on `isfile` on Strings longer than 255 characters is an error
> fix file link clicking

- src/requests/actions.jl
explicit version of the `@reexport` macro, will follow this with a version for within-source modules. e.g.
```julia
using CSTParser
```
becomes
```julia
using CSTParser
export CSTParser, ParseState, parse_expression
```
> add reexport action for packages

- src/requests/features.jl
- src/requests/hover.jl
- src/utilities.jl
- test/runtests.jl
- test/test_communication.jl
- test/test_document.jl
- test/test_hover.jl
- test/text_edit.jl
get_expr1 finds the expression at a given offset, choosing an identifier when lying in between two expressions. Fixes https://github.com/julia-vscode/julia-vscode/issues/925 and some other issues where hovers weren't appearing when the cursor was at the start of an expression.
> add alternative get_expr for hovers and definitions

- src/requests/init.jl
- src/requests/textdocument.jl
Fix for https://github.com/julia-vscode/julia-vscode/issues/919.
- Checks for number of julia files in workspace folders, it > 5000 doesn't attempt to load them.
- When loading files not already loaded to the server will attempt to find and load parent files that include the initial file
> For large folders, only load files on demand

- src/requests/misc.jl
required for https://github.com/julia-vscode/julia-vscode/pull/902 (probably)
> include trailing ws in getCurrentBlockOffsetRange

- Project.toml
- src/languageserverinstance.jl
- src/requests/misc.jl
- src/staticlint.jl
- test/runtests.jl
- test/test_hover.jl
Complements https://github.com/julia-vscode/SymbolServer.jl/pull/72. All seems to work :)
EDIT: There is another benefit of this approach: we should be able to eventually just have the JSON RPC layer and the symbol server put their messages into the same channel, and then the main message loop can just process both messages from the client _and_ from the symbol server, without the current design that we only handle symbol server messages when something happened on the main message queue.
> Async symbolserver

- src/languageserverinstance.jl
- src/requests/init.jl
- src/requests/textdocument.jl
- test/test_hover.jl
- test/text_edit.jl
The idea is that we now never call `write_transport_layer` anywhere, other than in the thread for message sending. Instead, we use `send` everywhere. The benefit is that we can call that from any thread, without messing up the output pipe. So we can for example now send messages back to the client from the thread that runs the async symbol server stuff etc.
Also fixed a number of other bugs that came up.
Once this is merged, I'll open a PR that a) sends crash reports from the symbol server and b) does the progress UI reporting stuff with the new LSP support for that.
> Send all messages via a queue

- src/requests/completions.jl
Previous ordering failed to treat modules with the respect they deserve (provided completions for fields of the `Module` type rather than the contents of the module)
> fix comps for user defined modules

- src/languageserverinstance.jl
- src/protocol/initialize.jl
- src/requests/init.jl
Fixes #494.
I read the spec again, and I think we do need to check to be spec conform. In particular, we are also sending a `window/workDoneProgress/create` request, and we should only do that if the client supports it.
> Detect whether client supports progress stuff

- src/languageserverinstance.jl
We should just let it crash if there is a bug in that place, right now we are hiding what is going wrong from crash reporting with this.
I might merge this right away and tag a new release, so that we can actually crash reports that tell us something useful..
> Remove a catch statement

- src/document.jl
- test/test_document.jl
Might help diagnose https://github.com/julia-vscode/LanguageServer.jl/issues/501.
I tried it once with a fake error, it seems to work. Not the nicest output, but hopefully we'll get what we need. Do you think this is sufficient?
> Add extensive error output for get_offset

- src/utilities.jl
Previously it was checking the offset (in bytes) against the length (in characters) of the document text.
Fixes: https://github.com/julia-vscode/julia-vscode/issues/955, but unrelated to other `get_offset` error
> fix to get_toks, offset > sizeof(text) should be caught earlier

- src/languageserverinstance.jl
- src/requests/textdocument.jl
This stops us sending lint message until we've loaded symbols. It's not clear to me whether the additional field is necessary or we could use one of the existing symserv related fields
> wait for symserv before sending lint errors

- src/requests/textdocument.jl
Fixes #522.
In general one should not index into a string with the return value of `sizeof`, that will not work with unicode charachters. I did a quick search of LanguageServer.jl for `sizeof` and it is used 39 times... We should probably take a look at every single instance and decide whether `lastindex` is more appropriate? And we should probably audit the other packages as well?
> Fix string indexing error

- docs/src/index.md
Currently these relative links give a 404 when followed from www.julia-vscode.org
> Fix links to wiki from rendered docs

- src/staticlint.jl
As far as I can tell, StaticLint should never try to set a doc that already exists, this just adds an error if it does so that we would see that in crash reporting. I think if I understand the code correctly, that branch should actually never be hit.
> Throw an error if StaticLint does something it shouldn't do

- src/utilities.jl
I think that `if` statement will always be `true`, right? So I removed it :)
> Use accessor and remove redundant check in remove_workspace_files

- src/document.jl
- src/requests/init.jl
Right now, if a file is open in the editor, and then someone adds a folder to the workspace, that file wouldn't be marked properly as belonging to the workspace.
> Make sure the workspace flag is always set properly

- src/requests/workspace.jl
Some problems with the current implementation:
- it did not properly handle create requests (in particular, if the doc was not already in `server.documents`, it did nothing)
- it did not mark deleted files as no longer in the workspace. That meant that if such a file was open in the editor, and then we received a `didClose`, this file would hang around in `server.documents`, even though it shouldn't.
> Fix the implementation of didChangeWatchedFiles

- src/requests/textdocument.jl
I'm going to merge right away so that I can cut a new RC. This came in via crash reporting and I hope the fix is simple enough :) `u` simply is a `URI2` already.
EDIT: And boy, we really need to write tests ;) v0.15.0...
> Remove buggy URI2 conversion

- src/requests/workspace.jl
We have a crash report with an event here that has a URI that starts with `git:`. I don't really understand why we would get that in the first place, but clearly we can't handle anything other than pure `file:` schema events here, so for now I'm just filtering on that.
This fix is hopefully good enough for the next release, I'm also following up upstream how we are supposed to handle that kind of thing...
> Only handle didChangeWatchedFiles for file: schema

- src/requests/init.jl
I have definitely experienced an orphan SymServ process (on linux). This could fix this, and seems safe in any case.
> Kill ss process on exit request

- src/LanguageServer.jl
- src/exception_types.jl
- src/languageserverinstance.jl
Fixes an error from crash reporting.
I'm also introducing a new exception type here. The crash reporting can distinguish different different exception types, so this way we don't lump all `ErrorExceptions` into the same bucket.
> Fix symbol server error handling on older Julia versions

- src/languageserverinstance.jl
- src/requests/init.jl
- src/requests/textdocument.jl
- src/requests/workspace.jl
- src/staticlint.jl
- src/utilities.jl
This attempts to fix a whole bunch of file IO bugs that are coming in via crash reporting.
It generally takes a different approch from how we did this in the past: instead of trying to check various conditions before we try to read a file, we don't check anything anymore, but just try to read the file and wrap that in an exception handler.
I think the previous approch fundamtenally can't work reliably: there is always a chance that between our call to check for example file permissions and our read call, something changes about the file, and then the read call will fail. So we must just always have a try catch around the `read` operation, no matter what. But then we might as well do away with the checks as well, given that those scenarios then are also handled by the exception handler. …
> Wrap all file IO in exception handler and check for invalid UTF-8 sequences

- src/languageserverinstance.jl
With this we still get crash reports when the symbol server process crashes, but it won't take the LS process down anymore. Instead, the LS process will just not have returned the symbol info we need, but other parts of the LS should still work.
> Don't crash the LS when the SymServer crashes

- src/document.jl
- src/requests/actions.jl
- src/requests/textdocument.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/564. Or at least I hope it does ;)
I essentially started from the code at https://github.com/microsoft/vscode-languageserver-node/blob/master/textDocument/src/main.ts and ported that over to Julia.
The main difference to the previous implementation is that offset is now always a valid Julia string index. The range in the edit chunk is the text that gets replaced (expressed as a Julia range that returns that text if used to index into the String). Generally the code is simplified, fewer `if` `else` stories in the whole `didChange` story, hopefully that makes this more robust.
I've only changed the text sync stuff over to the new offset interpretation, everything else still uses the old version. Not ideal, but I thought maybe we …
> Rework text sync

- src/requests/init.jl
- src/requests/textdocument.jl
- src/requests/workspace.jl
- src/staticlint.jl
When I added the more specific error handlers, I forgot to also adjust the validation phase accordingly. Fixes a bug from crash reporting.
I added some stuff, namely it is now also handling `SystemError` properly, because those can also happen from file IO problems.
> Fix UTF-8 validation and file IO error checking

- src/requests/completions.jl
- src/requests/features.jl
- src/requests/init.jl
- src/requests/textdocument.jl
- src/requests/workspace.jl
- src/staticlint.jl
Argh, this was meant to be part of the previous PR... 
In any case, we need to treat `IOError` and `SystemError` the same way, both can happen with file IO problems.
> Fix file IO error handling

- src/requests/completions.jl
- src/requests/init.jl
- src/requests/textdocument.jl
Fixes a bug from crash reporting, and I also added more checks around a couple other file IO operations. `isdir`, `ispath`, and `readdir` can all crash if there is an IO problem.
> Guard against more IO errors

- src/requests/completions.jl
* fixes latex support for superscripts
* adds latex support in comments
https://github.com/julia-vscode/julia-vscode/issues/1064
https://github.com/julia-vscode/julia-vscode/issues/1065
> Latex fixes

- src/exception_types.jl
- src/utilities.jl
We have some crash reports where the conversion doesn't work, this adds some diagnostics to our crash reports that hopefully will allow us to figure out what is going on.
> Add exception type for failed uri conversions

- src/requests/features.jl
- src/requests/textdocument.jl
Marking missing Symbols that use `var"something"` syntax
> mark var"" missings

- Project.toml
- src/utilities.jl
- test/test_paths.jl
~~This first requires a new version of URIParser with https://github.com/JuliaWeb/URIParser.jl/pull/68 merged.~~ New version of URIParser.jl is published.
In general this is the first step to support UNC paths on Windows. We currently have crash reports around that.
I mostly just followed the logic of the URI node package that VS Code uses.
> Support UNC paths

- src/languageserverinstance.jl
- src/requests/init.jl
I think this is how we are supposed to do this right now.
What is weird is that we then get a change notification for _any_ setting change (even say in the Python extension), but I don't think that should cause any problems. I have a question out to MS how we are supposed to handle that, but I think this PR in itself is correct already and we should just go ahead and merge to see whether this might solve the errors we get in crash reporting on this stuff.
Also needs https://github.com/julia-vscode/julia-vscode/pull/1157.
> Register for didChangeConfiguration

- src/requests/textdocument.jl
We are still seeing bugs in that part in the crash reporting... The weird thing is that we get the error for files that are not open in the editor, which I don't even understand how that is possible at all....
In any case, I'm out of ideas what might be wrong here, but maybe we can track it down if we can ask for more information...
> Add a request for help to tricky bug

- src/protocol/basic.jl
- src/protocol/protocol.jl
For some reason we were sending fields specified as missing in the  LSP to the client.
hat tip: @non-Jedi
> Don't send missing fields

- src/jsonrpc.jl
- src/jsonrpcendpoint.jl
- src/protocol/initialize.jl
This saves a dictionary lookup and is easier to read. This also may
make debugging #600 easier since there was a bug where
`response["error"]["data"]` was getting thrown away and
`response["error"]["code"]` used instead.
> Refactor ternary expressions to plain get

- src/languageserverinstance.jl
- src/requests/textdocument.jl
- src/requests/workspace.jl
- src/staticlint.jl
Simplified version of #683 or #666. Also did a bit of
refactoring. This avoids using `default_options` from StaticLint and
DocumentFormat which probably shouldn't be considered part of their
public API.
> Simplify configuration code

- src/exception_types.jl
- src/utilities.jl
Helps diagnose #703.
The general idea is that we want to figure out where relative paths come from, and this might help us to narrow that scenario down. My understanding is that we will never receive a URI from a client with a relative path, but that those relative paths originate somewhere in our own code, maybe in the include following logic of StaticLint? Of course, I would just generally remove any loading of non-workspace files from disc :)
CC @pxl-th and @non-Jedi.
> Add check for relative paths

- src/uri2.jl
- src/utilities.jl
- test/test_paths.jl
- Add function for escaping URI
- Add tests for escaping/comparing/hashing URI
This is a continuation of discussion in #699 PR, that allows comparing URIs that were created using different encoding schemes.
Basically what it does is it escapes URI to bring it to the same encoding scheme as in [vscode-uri](https://github.com/Microsoft/vscode-uri).
This allows for following comparisons:
```julia
hash(LanguageServer.URI2("file:///D:/FOO/bar")) == hash(LanguageServer.URI2("file:///d%3A/FOO/bar"))
```
It escapes only file URI, since I'm not sure if escaping is needed in other cases.
**Note:** It still needs to be checked if _"VS Code internally also treats two strings that stand for the same URI but use different encoding patterns as equal or not"_, so this may be considered as WIP.
> Add escaping when comparing/hashing URI2

- src/languageserverinstance.jl
Users of fully-capable clients (such as VS code) get a sense of the progress being made by `SymbolServer` while indexing packages. However, clients which don't have the capability to display progress notifications get no information whatsoever. This proposal falls back to simply displaying indexing progress on stderr for such clients.
This helps at least when using the `LanguageServer` within Emacs via `eglot`, which allows to easily display the server output for debugging purposes. I'm not sure whether there are other clients for which such additional output would be unwelcome...
> Fall back to displaying SymbolServer indexing progress on stderr

- src/languageserverinstance.jl
This was being called at the wrong point before and was failing to provide the correct list of extended methods.
> fix collec_extended_methods bug

- src/requests/workspace.jl
Leading to bugs in the wild right now, we should ship quickly.
> Add isnothing for Julia < 1.1

- src/requests/completions.jl
This should prevent gensymed variables being suggested for completions. This reminds me that completions don't works with the `var"someid"` syntax but that's not an immediate priority
closes #719
> don't suggest gensymed names for completions

- src/requests/hover.jl
We're still getting these errors and I couldn't recreate any from the EXPR so this includes the string representation of the code instead.
> change LSHoverError reporting

- src/languageserverinstance.jl
Using the `function(x)` syntax makes this callback clearer and doesn't
confuse indentation so much.
> Refactor -> anonymous function

- src/requests/misc.jl
fixes #716 ?
Changes the behaviour to ignore trailing white space when considering which block to retrieve. By default returns an empty selection at (0,0):(0,0). @pfitzseb , is this what was wanted?
> alter getCurrentBlockRange request

- src/requests/workspace.jl
The wrong configuration name was being requested, `kwspacing -> kwarg`.
Mentioned in https://github.com/julia-vscode/LanguageServer.jl/pull/753
> fix FormatOptions inconsistency

- README.md
- src/LanguageServer.jl
- src/runserver.jl
- test/test_communication.jl
runserver will attempt to pick a reasonable environment to run the
language server against.
Closes #748.
We still need to address running the language server against a project
with no Manifest.
Long term we also probably want to move away from the `env_path` being passed into the language server, but this at least makes things easier on clients until then.
> Introduce runserver function

- src/requests/actions.jl
- src/requests/features.jl
closes #763
This is because `WorkspaceEdit` is mis-specified within our version of the spec, what does: 
`ts { [uri: DocumentUri]: TextEdit[]; };` mean? 
Is it a vector of pairs `(DocumentUri, Vector{TextEdit})`?
> nothing -> missing in WorkspaceEdit

- src/requests/features.jl
This should be merged urgently, sorry all.
> fix use of StaticLint.iterate_over_ss_methods

- src/requests/textdocument.jl
- src/utilities.jl
- test/test_paths.jl
same as #776 
IDEA: how about making those "linting-disabled" dirs configurable by users ?
> disable lints for docs dir

- src/requests/features.jl
- src/utilities.jl
Returns a [command URI](https://code.visualstudio.com/api/extension-guides/command#command-uris) for links.
> Use a command URI for getDocAt

- src/requests/features.jl
- src/utilities.jl
The corresponding PR on the VS Code side is coming in a minute, I'll explain there.
> Use MD for julia_getDocAt_request, remove all VS Code specifics

- src/languageserverinstance.jl
Fixes a race condition that came in via crash reporting.
The problem is that during the `JSONRPC.send` call other tasks can set `server.current_symserver_progress_token` to `nothing`, and then we crash. Here we use a local variable now to for `send` calls, which ensures that we can't get into that state.
> Fix a race condition for progress tokens

- src/requests/features.jl
- src/requests/hover.jl
There is a cycle in the links (`.prev`/`.next`) between StaticLint.Bindings. The root cause is within StaticLint but there is no reason to allow it to crash the language server. If we have done a complete circuit here (i.e. a loop is detected) then we have all the information we need and can `return`.
As this is being hit quite a lot, this approach seems best for the user while the StaticLint bug is fixed. Thoughts?
> Escape from get_func_hover loop

- src/requests/features.jl
Next attempt to fix https://github.com/julia-vscode/LanguageServer.jl/issues/768.
This is kind of embarrassing because I completely forgot about the whole `offset` vs `offset2` thing in the code base... Here is the background story: we had a lot of text sync errors in the fall, so I rewrote the whole text sync logic, largely just copying the algorithm from the original MS node implementation. One thing I was never able to square was the original `get_offset` implementation we had and one that followed the MS logic (that is to say, I didn't really understand our implementation :) ). In the end I added the MS based implementation as `get_offset2` and used that for all the text sync stuff. That got rid of all the text sync bugs. I didn't remove the original `get_offset` implementation …
> Fix an offset bug

- src/requests/init.jl
Fixes a bug that showed up on azure:
```
MethodError: Cannot `convert` an object of type Nothing to an object of type String
Closest candidates are:
convert(::Type{String}, !Matched::FilePathsBase.AbstractPath) at /Users/.../.vscode/extensions/julialang.language-julia-0.17.8/scripts/packages/FilePathsBase/src/path.jl:107
convert(::Type{T}, !Matched::T) where T<:AbstractString at strings/basic.jl:209
convert(::Type{T}, !Matched::AbstractString) where T<:AbstractString at strings/basic.jl:210
at setindex!(::Dict{String,Nothing}, ::Nothing, ::Nothing) (dict.jl372)
at push!(::Set{String}, ::Nothing) (set.jl48)
at initialize_request(::LanguageServer.InitializeParams, ::LanguageServerInstance, ::JSONRPC.JSONRPCEndpoint) (./julialang.language-julia-0.17.8/scripts/packages/LanguageServer/src/reque …
```
> add another nothing check to initialize_request

- src/protocol/basic.jl
- src/protocol/features.jl
- src/protocol/goto.jl
- src/protocol/highlight.jl
- src/protocol/hover.jl
- src/protocol/initialize.jl
- src/protocol/signature.jl
- src/protocol/symbols.jl
refs: https://github.com/julia-vscode/LanguageServer.jl/pull/688
closes https://github.com/julia-vscode/LanguageServer.jl/issues/651
> Fix for ProgressToken typing

- src/LanguageServer.jl
- src/requests/actions.jl
- src/requests/init.jl
Defines a simpler interface for adding CodeActions (description within source). Removes the 'add default constructor' action.
> tidy up codeActions

- README.md
I've added a Wiki entry which describes a kakoune setup with julia lsp integration. This PR aims to link the new entry in the `README.md`
> include link to new Kakoune wiki entry

- src/requests/misc.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/771.
> improve getCurrentBlockRange

- src/requests/workspace.jl
The new client side lib version sends a new client id, and so our insider build is crashing at the moment. I'm going to merge this right away to fix that. Review after the fact would be great.
> Update to new client lib version

- src/document.jl
Will hopefully give us a better idea about a crash I saw in crash reporting.
> Add more diagnostics

- src/languageserverinstance.jl
the `meta.error` field for a Document's `EXPR` points to the doc itself (this allows us to get the file/line location from an isolated `EXPR`). It was being removed, breaking things (e.g. refs, definitions, etc)
> ensure parent doc is set

- src/requests/actions.jl
Only get offset for start of range, the end point isn't actually used by any of the actions anyway. 
Fixes a bug from Azure.
> only use range start offset

- src/protocol/completion.jl
Allow for `nothing` in CompletionContext.triggerCharacter
> special handling for CompletionContext

- src/requests/init.jl
Fixes an error we got on [Azure](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%2C%22Name%22%3A%22julia-vscode%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%2Fsubscriptions%2F6803c4ed-bcb4-41d4-bceb-7faf5e7a3469%2FresourceGroups%2FDefault%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fjulia-vscode%22%2C%22ResourceType%22%3A%22microsoft.insights%2Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%2298a89171-6c36-11eb-964c-77d7a7635906%22%2C%22timestamp%22%3A%222021-02-11T06%3A58%3A49.745Z%22%2C%22cacheId%22%3A%22d77d3cf7-d333-4d76-98c7-a6ad5fba5078%22%2C%22eventTable%22%3A%22exceptions%22%7D9).
~Ideally we'd …
> improve walkdir err handling

- src/document.jl
- src/requests/features.jl
Fixes https://github.com/julia-vscode/crashreporting-issues/issues/25.
I don't want to remove these kind of checks for code paths that are "crucial", like say doc sync. But I think for stuff like the get module story, we can be more forgiving. Not super happy, because it still seems to me that we have some bug upstream somewhere, but for now maybe this is ok.
> Add forgiving mode to get_offset2

- src/document.jl
Helps diagnosic https://github.com/julia-vscode/crashreporting-issues/issues/26.
We somehow end up with a relative path for a document there, so we need to figure out how that is slipping in.
> Add a diagnostic for relative paths

- src/document.jl
- src/requests/features.jl
- src/utilities.jl
by ensuring that the offset is inside (not on the edge of) the EXPR's span.
Fixes https://github.com/julia-vscode/julia-vscode/issues/1600 and similar issues (at least when the cursor actually is *outside* of the module definition).
> better getModuleAt

- src/languageserverinstance.jl
~Needs https://github.com/julia-vscode/JSONRPC.jl/pull/44.~
> better shutdown handling

- src/requests/features.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/912.
Turns out that `get_expr1` on the edge of an identifier sometimes returns the previous one. `get_identifier` doesn't.
> fix find_references

- src/requests/completions.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1988. 
Do we want to add an opt-out setting to this? Imho this is unintrusive enough not to need one (JS completions are always fuzzy as well). 
> allow fuzzy completions

- src/requests/hover.jl
Fixes the printing of kwargs in the hover widget.
Before:
After:
> fix kwarg hover printing

- src/requests/hover.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2108. Tested on Linux and Windows.
Also directly goes to the correct line for VSCode clients.
> fix markdown hover URIs for VSCode

- src/requests/features.jl
- src/requests/misc.jl
- src/utilities.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2078.
Now also has a few more improvements regarding the specifics of `getModuleAt` and `getBlockRange` around modules.
> fix in-module eval for mods with docstrings

- src/requests/completions.jl
Makes our kw completions consistent with all other completions. We now return
```
[Trace - 12:27:30] Received response 'textDocument/completion - (7)' in 422ms.
Result: {
"isIncomplete": true,
"items": [
{
"label": "import",
"kind": 14,
"documentation": "import",
"insertTextFormat": 2,
"textEdit": {
"range": {
"start": {
"line": 7,
"character": 0
},
"end": {
"line": 7,
"character": 3
}
},
"newText": "import"
}
}
]
}
```
for `imp\tab` instead of an empty range followed by the missing part of the snippet.
Ref https://github.com/fannheyward/coc-julia/commit/af04e94e0594fb87a5a2bd641ff8b87798a759cb.
> improve snippet completions

- src/requests/features.jl
- src/requests/highlight.jl
Factor out common code for https://github.com/julia-vscode/LanguageServer.jl/pull/908.
> Document highlight refactor

- src/requests/textdocument.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2175.
Also gets rid of the duplicated `Julia(Julia)` stuff at the end of the error message.
> cosmetically improve lint msges

- src/requests/completions.jl
Fixes [an issue from crash reporting](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%2C%22Name%22%3A%22julia-vscode-insider%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F6803c4ed-bcb4-41d4-bceb-7faf5e7a3469%252FresourceGroups%252FDefault%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252Fjulia-vscode-insider%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%22f2278151-c6ce-11eb-bc21-e9b6e5daa981%22%2C%22timestamp%22%3A%222021-06-06T13%3A56%3A09.025Z%22%2C%22cacheId%22%3A%22b6685c1c-657b-46ca-a954-a0e37a5c23bc%22%2C%22eventTable%22%3A …
> add nothing check to get_file_level_parent

- src/requests/hover.jl
The LSP client for Sublime Text doesn't support (anymore) the filepath:line format as it is used for Markdown link destinations to other files in hover results. There is some special casing by the server for VS Code to use a file URIs with a `#line` suffix, and those can be handled by the Sublime Text client (on the latest `main` branch) too, so this change would restore the functionality to open file links there. The name used in `clientInfo` is "Sublime Text LSP".
I haven't checked if the file URI format is supported by the other clients for Emacs/vim too, but perhaps this special check for VSCode (and now Sublime) could even be removed completely in favor of always using file URIs instead.
> Use file URIs for MD links in hover popups for Sublime too

- src/requests/completions.jl
Fixes an issue whereby completion items were duplicated. This prevents the addition of explicit imports for already imported symbols (e.g. Core symbols that are exported by Base).
> Don't duplicate completions

- src/multienv.jl
There were two problems: 1) it didn't use `Base.env_project_file`, and that symbol isn't exported, so I doubt this was ever even called, and 2) we need to handle a `Bool` return value.
I'm also not entirely sure whether the semantics I'm using here make a lot of sense, but it at least should fix a runtime error, hopefully.
> Fix env_project_file usage

- src/requests/hover.jl
- test/requests/hover.jl
because these are already indicated by highlighting the matching paren anyways.
> remove hover message for closing function call parenthesis

- src/multienv.jl
- src/protocol/messagedefs.jl
Fixes an issue from [crash reporting](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%2C%22Name%22%3A%22julia-vscode-insider%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F6803c4ed-bcb4-41d4-bceb-7faf5e7a3469%252FresourceGroups%252FDefault%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252Fjulia-vscode-insider%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%22edec0c20-ef3f-11eb-9455-897edacf0cc8%22%2C%22timestamp%22%3A%222021-07-28T01%3A05%3A41.041Z%22%2C%22cacheId%22%3A%22334bcabe-67dc-4237-bef5-6cba9da6a60f%22%2C%22eventTable%22%3A …
> additional error handling in get_env_for_root

- src/requests/workspace.jl
Fixes https://github.com/julia-vscode/crashreporting-issues/issues/46.
> Harden against files with embedded NULL

- src/requests/completions.jl
Fixes a [method error](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%2C%22Name%22%3A%22julia-vscode-insider%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F6803c4ed-bcb4-41d4-bceb-7faf5e7a3469%252FresourceGroups%252FDefault%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252Fjulia-vscode-insider%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel/%7B%22eventId%22%3A%22731a4fb5-07d7-11ec-bfec-a77f3c04ebb5%22%2C%22timestamp%22%3A%222021-08-28T08%3A10%3A47.524Z%22%2C%22cacheId%22%3A%2222efd05f-07cc-4ad2-908d-c17cf4e9a7fd%22%2C%22eventTable%22%3A%22exceptions%2 …
> fix CompletionState method error

- src/requests/actions.jl
- test/requests/actions.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2356
> add quickaction to remove unused farg name

- src/requests/features.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2303
Function-like objects were being rejected as valid bindings by `is_valid_binding_name` and so all symbols in their scope were escaping.
I don't know if it's the most intuitive but right now I have on `::TheType` for the name given to callable object symbols.
> Fix document symbols for function-like objects

- src/requests/hover.jl
- test/requests/hover.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2650
This assumes that if a docstring is present, then no matter what the preceding macros do, the docstring should still apply to the defined struct/method/binding.
```julia
"docstring"
@macro1 @macro2 foo(x) = x + 1 # assume "docstring" should still apply to foo(x)
```
Also adds a missing newline for hovers with single line docstrings on bindings. e.g
```julia
"docstring"
x = 123
```
> Fix hover docs for definitions in nested macros

- src/requests/features.jl
Patches #1029
style is not within JuliaFormatter.Options
> keep style option from .JuliaFormatter.toml

- src/requests/features.jl
This matches the old DocumentFormat.jl default.
Without this we will have a massive, massive reformatting happening all over the place via package butler.
> Make no whitespace around kwargs default

- src/requests/features.jl
- test/runtests.jl
- test/test_misc.jl
This is more inefficient but also more correct.
Crucially, we can't rely on the fact that iterating over `parentof(x)` will yield `x` at any point. This basically only comes up with generators, so it might make more sense to fix the iteration protocol instead.
> Fix get_file_loc for generators

- src/languageserverinstance.jl
This patch removes the wrapper that checks whether the server have been
requested to shut down for the exit notification message. This message
should be handled directly as is, since otherwise we never reach the
exit() call and the server stays alive in a useless state forever.
> Handle exit notification message correctly

- src/requests/completions.jl
Fixes an issue from crash-reporting:
``` 
StringIndexError:
at string_index_err(s::String, i::Int64) (string.jl:12)
at getindex_continued(s::String, i::Int64, u::UInt32) (string.jl:233)
at getindex (string.jl:226)
at is_latex_comp(s::String, i::Int64) (.\julialang.language-julia-1.6.10\scripts\packages\LanguageServer\src\requests\completions.jl:338)
at textDocument_completion_request(params::LanguageServer.CompletionParams, server::LanguageServerInstance, conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}) (.\julialang.language-julia-1.6.10\scripts\packages\LanguageServer\src\requests\completions.jl:58)
at (::LanguageServer.var"#97#98"{typeof(LanguageServer.textDocument_completion_request), LanguageServerInstance})(conn::JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, …
```
> More robust is_latex_comp

- src/requests/workspace.jl
This prints a debug log message if the client sends the
workspace/didChangeConfiguration request without claiming to support it.
> Print a debug message for unsupported request

- src/requests/actions.jl
- test/requests/actions.jl
This implements a new code action, CompareNothingWithTripleEqual, which
offers to replace == and != with === and !==, respectively, for the
corresponding linter warning(s).
> Implement code action to replace ==/!= with ===/!==

- src/requests/completions.jl
- test/requests/completions.jl
This implements completions for string macros to allow them to complete
without the initial `at` and trailing `_str`. For example, `artif`
completes to `artifact"` like in the REPL. If the completion mode is set
to `:import` the real name is imported (`using Pkg: at-artifact_str`),
and when the completion mode is `:qualify` the qualified string macro is
inserted (`Pkg.artifact"`).
> Completion for string macros

- src/requests/actions.jl
No functional change, the [`textDocument/codeAction`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction) just returns `CodeAction`s instead of `Commands` if the client supports it. All (currently) implemented actions in LS.jl can be losslessly converted to `Command`s. The advantages (action kinds, returning text edits without command roundtrip, etc) of returning `CodeAction` instead of `Command` are not implemented in this PR.
> Return code action literals instead of commands if client supports it.

- src/requests/actions.jl
This sends the .isPreferred property to the client if it supports is.
Currently only the action replacing == with === is marked as preferred,
since the other current ones are more situational.
> Implement basic support for CodeAction.isPreferred

- src/protocol/completion.jl
- src/requests/completions.jl
- src/requests/hover.jl
- test/requests/completions.jl
> Show type in completion details

- src/requests/actions.jl
- test/requests/actions.jl
This could potentially also have an accompanying more complex action
that removes the full assignment expression, but since it is difficult
to detect side effects etc that can not be a quickfix for silencing the
linter error. Replacing with _ should always be safe, however.
> Implement quickfix action to replace unused assignment name with _.

- src/protocol/configuration.jl
Fixes a bug from crash reporting related to the new uri stuff.
> Type a field correctly as DocumentUri

- src/URIs2/URIs2.jl
- src/requests/actions.jl
I am confused how CI passed without this, this path should be tested by https://github.com/julia-vscode/LanguageServer.jl/blob/0955a4d6e6bf1f88809054f4b18e9674445f1ad3/test/requests/actions.jl#L8 etc.
> Fix missing URI conversion in code action execution.

- src/document.jl
- src/requests/init.jl
The three-arg method wasn't properly forwarded to TextDocument.
> Fix index-at forwarding

- src/requests/actions.jl
- test/requests/actions.jl
This adds a new action for adding a SPDX short form identifier[0] to the
top of the file. The action is active when cursor is at the first line
of the file.
To find the correct license identifer the action first checks in the
tracked documents for existing identifers. This code path supports any
valid identifer for any license. If no such headers are found, the
action falls back to looking in license files in the current workspace
folders. Identification from the license file is currently done by a
heuristic, but this should be OK since the action is invoked by a human,
and not done automatically. Currently only MIT license can be detected
through license files.
[0]: https://spdx.dev/ids/
> Action for adding SPDX header.

- src/protocol/features.jl
- src/requests/actions.jl
- test/requests/actions.jl
This organizes the using/import statement under the cursor, together
with any older/younger sibling expressions. The output format is close
to 'BlueStyle': import before using, and sorted alphabetically.
> Implement basic code action for import/using organization.

- src/document.jl
- src/textdocument.jl
- test/test_document.jl
`Document` doesn't have a `._uri` field any more. In addition, defining
methods for `display(::X)` is rather unconventional, so this replaces
two such methods of `display` with `Base.show(::IO, ::MIME, ::X)`.
> Replace broken display methods with working show methods.

- src/requests/actions.jl
- test/requests/actions.jl
Was erroring before. Could be allowed, but IMO makes sense to disable that action for docstring strings.
> Fix string conversion code action in docstrings

- src/requests/actions.jl
In the future it would be better to present multiple actions to the
user, if a symbol exist in multiple modules. As a stopgap this just
returns early and applies the first found module.
Fixes #1087.
> Return early in apply missing reference action

- src/requests/features.jl
This catches errors from parsing the .JuliaFormatter.toml.
Fixes https://github.com/julia-vscode/julia-vscode/issues/2905
> Prevent language server crashes for invalid .JuliaFormatter.toml

- src/URIs2/URIs2.jl
Fixes #1103.
I'm not super happy about this implementation (also never was about the previous one), as it feels off to have this code as part of the `URI` type. But for now, good enough.
> Make URI case insensitive for files on win

- src/document.jl
- src/textdocument.jl
- test/runtests.jl
- test/test_document.jl
- test/test_edit.jl
> apply_text_edits: make sure indices are computed with updated document.

- src/requests/actions.jl
- test/requests/actions.jl
This patch contains fixes for the following two errors in in the
organize imports action when used on local modules:
- `using .Foo` formatted erroneously as `using ..Foo`
- `using .Foo: bar` tried to format `using ..Foo: bar`, but since this
is not a valid Julia expression this errored and crashed the language
server
> Fixes for organize imports with local modules

- src/requests/misc.jl
Should fix this error reported on slack:
```
ERROR: type Nothing has no field captures
Stacktrace:
[1] getproperty
@ .\Base.jl:42 [inlined]
[2] splitdrive(path::String)
@ Base.Filesystem .\path.jl:39
[3] joinpath(paths::Tuple{String, String})
@ Base.Filesystem .\path.jl:269
[4] joinpath(::String, ::String, ::Vararg{String})
@ Base.Filesystem .\path.jl:327
[5] find_document_links(x::CSTParser.EXPR, doc::LanguageServer.Document, offset::Int64, links::Vector{LanguageServer.DocumentLink})
@ LanguageServer c:\Users\Marcin\.vscode-insiders\extensions\julialang.language-julia-insider-1.6.28\scripts\packages\LanguageServer\src\requests\misc.jl:102
[6][ Info: Loading InlineStrings from cache... (0%)
find_document_links(x::CSTParser.EXPR, doc::LanguageServer.Document, offset::Int64, …
```
> Add isvalid check to find_document_links

- src/document.jl
- src/requests/features.jl
- src/requests/misc.jl
- src/requests/textdocument.jl
- src/textdocument.jl
- src/utilities.jl
This adds a new _language_id field to TextDocument, which
can be queried downstream. It's important to not look at
line endings here, because the client may set the language
to some arbitrary value which may or may not match
the extension.
An added bonus is that we don't try to parse quite as much 
invalid julia code -- the previous implementation would try to 
parse each markdown file as Julia and then extract Julia code
blocks from that.
> Fix  (julia)markdown parsing

- src/juliaworkspace.jl
- src/requests/init.jl
- src/requests/textdocument.jl
- src/requests/workspace.jl
- src/staticlint.jl
- src/utilities.jl
Should fix a crash reporting bug, plus I added the same check in all places where we call `isvalid` as that seems what we want.
> Add more checks for NULL in strings

- src/utilities.jl
Fixes a crash report. `tryparse` for UUIDs was added in Julia 1.6.
> Vendor tryparse for UUIDs pre 1.6

- src/requests/features.jl
VS Code seems to filter this in the UI, but that is not happening in neovim so perhaps this should be handled in the UI? But I don't see a reason to return duplicates since they don't contain any other information such as which of the methods on that line they represent etc.
> textDocument/definition: do not return duplicate locations.

- src/juliaworkspace.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/1152.
> Do not crash on invalid UUID entries

- src/requests/textdocument.jl
Dump the mismatch to the logger since it is pretty difficult to debug otherwise, in particular remotely (#1162).
> Dump the file content to the logfile when texts mismatch.

- src/requests/textdocument.jl
Follow up to #1164. Seems difficult to convince the logger not to truncate the string, so print directly to stderr.
> Print content directly to stderr instead of using logging

- src/utilities.jl
`-32099` is actually in the reserved range of error codes, and for example is already used by the ls client library that we use in the extension on the Typescript side of things for a different error condition, so one can no longer differentiate between these error conditions on the client side.
This now uses an error code that should be outside any reserved range. Technically we'll need to tag a major version, unless we are very positive that no client other than VS Code is using this functionality?
Also needs a corresponding PR on the extension side.
> Use unreserved error codes

- src/requests/features.jl
- src/utilities.jl
- test/requests/test_features.jl
- test/test_shared_init_request.jl
- test/test_shared_server.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/1180, https://github.com/julia-vscode/LanguageServer.jl/issues/1187, https://github.com/julia-vscode/LanguageServer.jl/issues/1188, and probably https://github.com/julia-vscode/LanguageServer.jl/issues/1184
Here is the idea:
1. We take as input the entire file and the range that should be formatted.
2. We enclose the given range by injecting two markers in the form of comments to the input file.
3. We format the result of step 2 (entire file with markers) using JuliaFormatter.jl. The output should include the injected markers.
4. We replace the given range in the input file with the code inside the markers of the output of step 3, and return this.
This approach avoids the need of having to deal with EXPRs and formats the given …
> Fix range formatting

- src/requests/hover.jl
- test/requests/test_hover.jl
Names of a qualified function calls were not displaying in hover text.
Before  
After
> Fix hover on arguments of qualified call

- src/requests/init.jl
Emacs crashes the language server by sending a null for initialize_request's initializationOptions.
Adding `!== nothing` to the `if` block fixes that.
> add check for nothing in init params to support emacs

- src/requests/hover.jl
previously, we were not looking at references when determining the list of methods defined for any given function, which means that `sin` only reported one method in the hover (because that's the only method that is defined directly in Base, the others are in Base.Math or LinearAlgebra).
> fix: show all methods in function hovers

- test/requests/test_completions.jl
A get field completions test would pass even if incorrect (note the line number change in the `struct T` test) since `all` of the empty generator is true.
> Fix completion test

- README.md
This PR adds Kate to the list of supported editors. The wiki has already been updated with an entry about how to use it and what to prepare.
NB: The PR ([here](https://invent.kde.org/utilities/kate/-/merge_requests/1324)) has just been merged recently, so it will take a bit of time until most users' Kate installations will have the default settings available to them. In the meantime the setting can be easily added by hand (about which I will add a note to the wiki as well).
> Add Kate editor to list

- src/languageserverinstance.jl
- src/requests/textdocument.jl
We don't want to sic CSTParser on toml files (or our linter, for that matter), so this PR makes sure to only parse/lint Julia or markdown files.
> fix: stop parsing and linting toml files

- src/languageserverinstance.jl
- src/requests/init.jl
- src/utilities.jl
This isn't used by VS Code afaict, but mentioned in the LSP docs
> To support the case that the editor starting a server crashes an editor should also pass its process id to the server. This allows the server to monitor the editor process and to shutdown itself if the editor process dies.
> feat: monitor editor pid for exit

- src/requests/actions.jl
This commit does these things:
* Add rudimentary detection of EUPL-* licenses
* Add logging statements throughout the action to make it debuggable should some license not be properly detected
* Fix a bug with SPDX header detection in existing files
To expand on the last point - previously, the header detection didn't have multiline matching enabled on its regex, which meant that any file having any lines other than the SPDX header wasn't detected as actually having a header. That's a bit bad, since presumably there would be actual source code following that header.
For a visual example, before:
After:
As for tests - I looked at `test/requests/test_actions.jl` and found an extremely minimal test for that action. I have no idea how to add a test for the functionality there, so I'd …
> Add better support for SPDX headers

- src/requests/init.jl
Adds a minor check for `params.capabilities.window.workDoneProgress`. 
This was done because some editors only partially support this optional protocol.
> Add check for `params.capabilities.window.workDoneProgress`

- src/requests/actions.jl
This patch changes the organize import action to put any self-bindings first in the sorted import list. Before this patch sorting results in
```julia
using Example: AbstractThing, Example
```
and after the patch
```julia
using Example: Example, AbstractThing
```
> Organize imports: put module self-binding first

- src/languageserverinstance.jl
> fix: disable type hints by default

- src/precompile.jl
The current precompile starts lots of tasks that never terminate, which doesn't play well with precompile.
> Disable precompile workload

- src/requests/workspace.jl
Fixes #.
lsp crashed and checked logs i found UndefVarErrors for `ksp` , guessing this is a typo.
> typo fix which sometimes causes lsp to crash

- src/protocol/configuration.jl
- src/protocol/initialize.jl
- src/requests/init.jl
- test/test_shared_init_request.jl
Down the road we can expand that to also watch files outside of the workspace, which actually works now.
> Use watch files client capability

- src/requests/init.jl
Closes #1310.
Disclaimer: only tested on Windows.
> Fix server doesn't initialize

- src/requests/completions.jl
This PR is a suggestion to implement and close #1282.
I have used this locally for a while and did not experience any drawbacks.
Regarding this comment from https://github.com/julia-vscode/LanguageServer.jl/issues/1282#issuecomment-2096217145
> This is an ok solution for the symptom, but imho the more correct fix here is to not offer the current binding. Otherwise you wouldn't get these somewhat useful completions:
It seems that this is not the case, i.e. functions from Base and also from other imported/used packages are still suggested, even when they match exactly. This is regardless whether the module name is prepended (e.g. `Base.sin`) or not (`sin`). Apparently those completions are added in a different code path. For the `Base.sin` example probably in …
> Exclude exact matches from user defined identifier completions

- src/languageserverinstance.jl
Fixes julia-vscode/julia-vscode#3721
> Send `WorkDoneProgressEnd` after `SymbolServer.getstore` reaches 100%
