julia-vscode/LanguageServer.jl

- src/provider_completions.jl
- src/provider_definitions.jl
These are two bug fixes that were made in julia-vscode after this repo was split out. I think these two are all there is, but might make sure to double check.
> Port fixes

- src/document.jl
- src/parse.jl
- src/protocol.jl
- src/provider_diagnostics.jl
- src/provider_misc.jl
- src/utilities.jl
- test/runtests.jl
- test/test_document.jl
Not ready for merging, I'm in the middle of this. Just wanted to give @ZacLN a heads up what I'm working on right now.
I'll write up an explanation about these changes once they are done. The broad idea is to a) encapsulate the ``Document`` type a bit more, so that it a) can be unit tested more easily, b) cut down on the number of allocations and c) make more use of the julia ``String`` code. But I'll provide a more thorough write up later. I hope to get this done later today.
> Make Document type more self-contained

- src/document.jl
- src/parse.jl
- src/protocol.jl
- src/provider_completions.jl
- src/provider_diagnostics.jl
- src/provider_misc.jl
- src/utilities.jl
- test/runtests.jl
- test/test_document.jl
Second attempt at #4. This should fix the bugs related to empty documents, at least the ones I found. Ready for review, @ZacLN.
> Make Document type more self-contained 2

- src/provider_completions.jl
Including the unicode character as the label doesn't seem to work so I've added it as a doc.
> add unicode symbol as doc, cleanup code

- src/document.jl
- src/protocol.jl
- src/provider_misc.jl
- src/utilities.jl
- test/test_communication.jl
- test/test_document.jl
Goes together with JuliaEditorSupport/julia-vscode#116.
> Workspace level doc handling

- src/provider_hover.jl
> fix hover offset

- src/provider_symbols.jl
fixes a spelling mistake as well
> reparse on symbol provider

- src/cache.jl
This makes things a lot faster on my system.
> Increase performance of sig function

- src/cache.jl
- src/languageserverinstance.jl
> Remove disc cache code

- src/cache.jl
- src/provider_misc.jl
I couldn't get things to work without this on my machine...
> Use base64 encoding for communication

- src/cache.jl
- src/languageserverinstance.jl
- src/provider_misc.jl
This goes hand in hand with JuliaEditorSupport/julia-vscode#149.
> Fix JULIA_PKGDIR for child processes

- test/runtests.jl
I don't think this is needed anymore, right?
> Remove unnecessary test code

- src/lint.jl
Same function defined just above.
> Remove duplicate function definition

- src/provider_misc.jl
This doesn't fix #65 but it seems sensible to move this to after the initialisation process anyway
> move parsing to after initialisation

- src/lint.jl
> Fix a windows path error

- appveyor.yml
I'm getting impatient, plus I don't think we need to track master while it is being worked on. This just matches the travis CI thing we are doing.
> Only test on julia 0.6 on appveyor

- src/lint.jl
I'm not sure if a similar change needs to be made on the windows side?
> fix lint-package path

- src/provider_action.jl
Adds command to apply all diagnostic actions of the same type to a file
> apply multiple actions

- src/provider_misc.jl
fix loop over key/value of dict
> fix dict iter

- src/provider_references.jl
References highlights were off by one
> fix references offset

- src/provider_misc.jl
- test/test_communication.jl
Doh! I'd forgotten how the line offsets worked when I made the previous PR.
> Use full document text syncing between client and server

- src/provider_hover.jl
- src/trav/local.jl
Hovering over an `end` keyword will tell you what sort of expression it closes
> add end hovers

- src/trav/lint.jl
Counterpart in CSTParser is [here](https://github.com/ZacLN/CSTParser.jl/commit/77e81a484c0647761f6d3d37464ff02927353571)
> Move linting from CSTParser to here

- src/trav/lint.jl
Adds diagnostic warnings and automatic fixes for the easiest to detect deprecations
> deprecation linting

- src/languageserverinstance.jl
Oops, last PR introduced an infinite loop in certain cases
> fix infinite linting loop

- src/trav/lint.jl
in IDENTIFIER lint, check against imported module names
> import linting fix

- src/provider_misc.jl
- src/trav/lint.jl
- src/trav/toplevel.jl
- didChangeFile response wasn't parsing files, this may help w/ change of git branch issue
- lint `include` calls to check for file in workspace
- change file-> uri for clarity in `toplevel` function
> fix didChangeFile, change symbol name for clarity, lint `include` calls

- src/provider_references.jl
- src/trav/local.jl
- src/trav/toplevel.jl
Improves the logic for references (and `rename`)
> improve refs/rename logic

- src/provider_misc.jl
ls side of https://github.com/JuliaEditorSupport/julia-vscode/pull/263
> add toggleFileLint request handler

- src/provider_misc.jl
- src/trav/toplevel.jl
also fixes a vector access bug
> move linting on startup

- src/trav/lint.jl
- src/trav/local.jl
Fixes the issue that Sebastian Pfitzner brought up on slack
> fix iteration over sig arguments

- test/runtests.jl
Pulls all test results into one table, pure UI improvement.
> Wrap all tests in a testset

- src/provider_misc.jl
> add julia/getCurrentBlockOffsetRange

- src/provider_misc.jl
Sadly it was too unreadable split across only two lines...
> eval inner block when inside modules

- src/utilities.jl
I think this might fix https://github.com/JuliaEditorSupport/julia-vscode/issues/393, but I'm not sure because I can't reproduce that error on my Windows system.
> Fix spaces on non-Windows

- src/jsonrpc.jl
- src/languageserverinstance.jl
- src/protocol/basic.jl
- src/provider_misc.jl
- test/test_hover.jl
Alright, this seems to mostly work.
I think I still saw an error at some point, but maybe we'll merge this for now and go from there?
> Multi root workspace

- src/languageserverinstance.jl
- src/provider_misc.jl
files or folders can be ignored by adding to : 
```
"julia.lintIgnoreList": [
],
```
I'll follow this with some explorer context menus on the client side to allow gui adding of files to the list
> Add ignorelint list

- src/LanguageServer.jl
Temporary fix for inference error, I'll try and get a mwe and open an issue upstream
> work around for inference/error printing error

- src/provider_definitions.jl
> handle `nothing` returned from find_source_file

- src/LanguageServer.jl
This accidentally slipped in, following discussions that it definitely shouldn't
> remove added convert method

- src/LanguageServer.jl
- src/protocol/configuration.jl
- src/requests/init.jl
Necessary to get LanguageServer working for
autozimu/LanguageClient-neovim
> Make fields in TextDocumentClientCapabilities nullable

- src/requests/textDocument.jl
fix user defined signatureHelp
> fix user defd sigs

- src/languageserverinstance.jl
- src/parsing.jl
- src/requests/textDocument.jl
- src/utilities.jl
This continues the purge of global variables.
@ZacLN  I'm going to merge this one here because it is not that much code, but could you still review this whether it is actually correct? It seems to work...
> Update to track global var-less StaticLint

- README.md
- src/languageserverinstance.jl
> Document arguments to LanguageServerInstance

- src/LanguageServer.jl
- src/languageserverinstance.jl
- src/requests/misc.jl
- src/utilities.jl
Parallel use of SymbolServer
Requires https://github.com/julia-vscode/SymbolServer.jl/pull/36
> WIP: support for parallel version of SymbolServer

- src/requests/features.jl
> fix definitions for imports of user specified mods

- src/requests/completions.jl
Non exported names were accidentally being suggested
> fix completions

- src/requests/completions.jl
- src/requests/features.jl
- Completions weren't suggesting all available symbols
- SigHelp bug fixed
> fix dot completions and sighelp bugs

- src/requests/hover.jl
Needs a bit of tinkering.
Shows the name of field being completed when constructing structs with a large number of fields (> 4). e.g. below hovering on any args used in the constructor would tell you which field they fill. 
Also currently tells you the number of the argument currently being hovered on (this seems less useful).
```julia
struct ManyFieldedDataType
field1
field2
field3
field4
field5
end
ManyFieldedDataType(arg1, arg2, arg3, arg4, arg5)
```
> add DataType constructor field hover

- Project.toml
- src/utilities.jl
To interact with https://github.com/julia-vscode/CSTParser.jl/pull/118, may require version changes
> Handle NONSTDIDENTIFIERs with get_expr

- src/requests/actions.jl
- src/requests/init.jl
- src/requests/workspace.jl
- src/utilities.jl
Only calculate effects of an action after it's selected - preemptive for when there are more actions
> refactor codeActions to use Commands

- src/requests/completions.jl
fixes https://github.com/julia-vscode/julia-vscode/issues/937
> fetch documentation for completions

- src/requests/completions.jl
- src/requests/hover.jl
- src/utilities.jl
- test/test_hover.jl
Converts code blocks from jldoctest to julia and attempts to use smaller headers inline with https://github.com/julia-vscode/julia-vscode/issues/936.
Will likely need to be finessed at some point
> clean up markup for hovers/completions

- Project.toml
- src/LanguageServer.jl
- src/jsonrpcendpoint.jl
- src/languageserverinstance.jl
- src/requests/actions.jl
- src/requests/completions.jl
- src/requests/features.jl
- src/requests/hover.jl
- src/requests/init.jl
- src/requests/misc.jl
- src/requests/textdocument.jl
- src/requests/workspace.jl
- test/test_communication.jl
- test/test_hover.jl
- test/text_edit.jl
@ZacLN This is a complete rewrite how we handle messages :) Not working yet, just wanted to give you a heads up that it exists.
The basic idea is to get our JSON RPC implementation in order. So this will properly handle responses, correlate them with a request etc. It should greatly simplify the API we have and make things more robust at the same time.
> Add JSONRPCEndpoint

- src/LanguageServer.jl
- src/jsonrpcendpoint.jl
- src/languageserverinstance.jl
- src/requests/init.jl
~~Doesn't work yet, waiting on https://github.com/microsoft/vscode-languageserver-node/issues/556 currently.~~
EDIT: @ZacLN this is ready for review, it all seems to work on my machine. We get a nice UI in the status bar with a spinning thing.
> Add progress reporting

- src/languageserverinstance.jl
missed something when copy/pasting
> fix missing statement

- src/languageserverinstance.jl
> Add one info message

- src/requests/completions.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/954
> sanitize completion docs

- src/requests/init.jl
- src/requests/textdocument.jl
- src/utilities.jl
https://github.com/julia-vscode/LanguageServer.jl/issues/508
> try to add some robustness on reading from disk

- src/requests/actions.jl
- src/requests/completions.jl
closing https://github.com/julia-vscode/julia-vscode/issues/967
> fix completions for text-operator completions 

- src/requests/features.jl
Goes w/ https://github.com/julia-vscode/StaticLint.jl/pull/94
> collect defined operators for documentSymbols

- src/requests/features.jl
https://github.com/julia-vscode/LanguageServer.jl/issues/520
> fix field access error closes #520

- src/languageserverinstance.jl
- src/requests/actions.jl
- src/requests/completions.jl
- src/requests/features.jl
- src/requests/hover.jl
- src/requests/init.jl
- src/requests/misc.jl
- src/requests/textdocument.jl
- src/requests/workspace.jl
- src/staticlint.jl
- src/utilities.jl
- test/debug.jl
- test/test_bruteforce.jl
- test/test_hover.jl
- test/text_edit.jl
This should be the uncontroversial stuff. ~~I'll have one more look before it is ready for review.~~
Ready!
> Only accessors

- src/requests/workspace.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/556.
It also changes the logic in more general ways: if the doc already exists in `.documents`, then it uses `set_text!` to update the content, rather than creating a new `Document`. I think that makes more sense?
~~EDIT: Also, note to self, I need to actually test this code before I merge it, this was coded blind and not tested.~~ Done, seems to work on my system. @ZacLN, ready for review!
> Fix didChangeWatchedFiles

- src/requests/completions.jl
> PackageRef completion fix

- src/requests/misc.jl
Fix for https://github.com/julia-vscode/julia-vscode/issues/1019. There were some bad off by one errors
> fix getCurrentBlockRange

- src/requests/textdocument.jl
Might help us pin down what is going on in https://github.com/julia-vscode/LanguageServer.jl/issues/564.
> Add more diagnostics for version mismatch case

- src/requests/completions.jl
- src/utilities.jl
This applies the same fix as was used previously to address an bug in julia <1.3
> splitdir fix, closes #573

- src/jsonrpcendpoint.jl
This won't fix https://github.com/julia-vscode/LanguageServer.jl/issues/571, but it should tell us what is going wrong.
> Handle errors at the JSON RPC level

- src/protocol/initialize.jl
- src/requests/init.jl
> fix to make it work with lsp-julia

- src/requests/completions.jl
- src/requests/features.jl
- src/requests/init.jl
- src/requests/textdocument.jl
- src/requests/workspace.jl
- src/staticlint.jl
This should fix some bugs from crashreporting and also generally make our IO error handling story more robust.
> Improve IO error handling

- src/requests/workspace.jl
Fixes a bug from crash reporting.
> Don't crash on delete msg for non existing file

- src/languageserverinstance.jl
Goes with https://github.com/julia-vscode/SymbolServer.jl/pull/114.
> Improve progress report symserver and harden against segfaults

- src/requests/hover.jl
Closing https://github.com/julia-vscode/LanguageServer.jl/issues/606
https://github.com/julia-vscode/LanguageServer.jl/issues/605
> add safety check for get_fcall_pos

- Project.toml
- src/languageserverinstance.jl
- src/requests/actions.jl
- src/requests/completions.jl
- src/requests/features.jl
- src/requests/hover.jl
- src/staticlint.jl
- test/test_hover.jl
https://github.com/julia-vscode/SymbolServer.jl/pull/123/
> update for SS changes

- src/requests/init.jl
> Remove dynamic reg for a client capability

- src/requests/hover.jl
- src/utilities.jl
An interim solution to : https://github.com/julia-vscode/LanguageServer.jl/issues/622.
This resolves operators only when you hover on them so that we get some documentation
> resolve operators on request for hovers

- src/requests/hover.jl
https://github.com/julia-vscode/LanguageServer.jl/issues/623
> return nothing instead of empty hover

- src/protocol/basic.jl
- src/protocol/completion.jl
- src/protocol/configuration.jl
- src/protocol/document.jl
- src/protocol/features.jl
- src/protocol/formatting.jl
- src/protocol/goto.jl
- src/protocol/highlight.jl
- src/protocol/hover.jl
- src/protocol/initialize.jl
- src/protocol/protocol.jl
- src/protocol/signature.jl
- src/protocol/symbols.jl
- src/requests/completions.jl
- src/requests/features.jl
- src/requests/init.jl
- src/requests/textdocument.jl
- src/requests/workspace.jl
Adds everything from the 3.15 spec.
> update to LSP3.15

- src/languageserverinstance.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/631.
I have to admit I don't understand how we can get into a state where the token might be `nothing`, but these checks can't hurt.
> Add some checks around sending notifications

- src/requests/features.jl
fixes: https://github.com/julia-vscode/julia-vscode/issues/1143
> fix find_references logic - add missing brackets

- src/requests/completions.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/638, I hope.
> Fix string indexing error

- src/requests/completions.jl
https://github.com/julia-vscode/LanguageServer.jl/issues/620
> add completions for convenience module bindings

- src/exception_types.jl
- src/requests/hover.jl
> wrap hover fallback in try block

- src/document.jl
- src/exception_types.jl
We get these a fair bit, just want to classify them in the crash reports :)
> Add an exception type for an error

- Project.toml
- src/languageserverinstance.jl
This first needs a new minor version of SymbolServer.jl with https://github.com/julia-vscode/SymbolServer.jl/pull/146 merged.
> Add option for symbol server store path

- src/requests/textdocument.jl
> fix didClose file deleting logic

- src/requests/actions.jl
> fix single line function expansion

- src/languageserverinstance.jl
> Fix crash on textDocument/didClose

- src/languageserverinstance.jl
Small change to make this look more like the other places where `scopepass` is called :)
> Make a piece of code easier to understand for DA

- src/requests/features.jl
> fix goto def for imported DataTypes

- src/languageserverinstance.jl
- src/requests/init.jl
- src/requests/workspace.jl
> Check client accepts workspace/config requests

- src/staticlint.jl
Re- https://github.com/julia-vscode/StaticLint.jl/pull/170
> Make sure we can't load empty paths

- src/requests/workspace.jl
> change workspace/config check

- src/requests/workspace.jl
This fixes a number of bugs in the config handling:
1. For VS Code, it now only interprets a missing value for `bool` fields as `false`, otherwise it uses the default value for that field.
2. Previously for VS Code if a value came back, the code used the default value instead of the value returned from the client.
3. The previous logic for checking whether the linter should rerun was incorrectly ordered so that the test always returned false.
4. It now also includes changes in `lint_missingrefs` and `runlinter` as triggers for rerunning lint.
Would also be good to get this one out relatively quickly, I think this is affecting a lot of users.
> Fix config handling

- src/languageserverinstance.jl
- src/requests/textdocument.jl
- Make sure we clear meta data from cst when deleting files (i.e. possible links between bindings/refs).
- Don't delete diagnostics when we close a file
> some minor doc handling changes

- src/requests/completions.jl
fixes https://github.com/julia-vscode/julia-vscode/issues/1245
> enable path completions on homedir

- src/requests/features.jl
- test/runtests.jl
- test/test_intellisense.jl
> fix off by one in sig helper

- src/utilities.jl
> pre-empt incoming staticlint change

- src/requests/hover.jl
- src/utilities.jl
Bug from azure. Also replaces a loop with a recursive call.
> Remove while loop, fix symbol lookup

- src/protocol/configuration.jl
> add special JSON handler for DidChangeConfigurationParams

- src/requests/actions.jl
#765 did not fix #763. But this should do it now.
> Fix WorkspaceEdit (again)

- src/requests/features.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/767.
I'm not sure when this can happen, but should fix the crash regardless.
> more careful getModuleAt

- src/exception_types.jl
- src/requests/features.jl
- src/requests/hover.jl
- src/requests/textdocument.jl
- src/utilities.jl
In order to identify infinite loop/memory leak
> replace loops with recursion

- Project.toml
I'm going to merge right away.
> Add SymbolServer 5 to compat

- src/requests/hover.jl
As per the bug detailed in https://github.com/julia-vscode/julia-vscode/pull/1308
> fix displaying of docs on hover

- src/LanguageServer.jl
- src/extensions/extensions.jl
- src/extensions/messagedefs.jl
- src/protocol/document.jl
- src/protocol/messagedefs.jl
As requested by @ZacLN in https://github.com/julia-vscode/LanguageServer.jl/pull/778#issuecomment-652434721.
> move julia specific LS extensions to seperate dir

- src/requests/features.jl
- src/requests/hover.jl
- src/utilities.jl
- shows documentations for `const` variables
- follows up #744
> show document for `const` variables, follow up #744

- src/languageserverinstance.jl
- src/requests/textdocument.jl
- src/requests/workspace.jl
requires https://github.com/julia-vscode/julia-vscode/pull/1452
> make disabled directories configurable

- src/runserver.jl
> Use proper string for expansion to default env

- src/requests/init.jl
Might or might not help with the `get_offset` issues...
> disable incremental document updates

- src/requests/completions.jl
- src/requests/init.jl
- easy trigger of path completions
- more eager completion of macros
so that we get (note completion trigger characters):
---
This PR only contains small patches, but they're not obviously "bug fixes" so I'm totally okay with deferring merging.
> enhance completions:

- src/requests/completions.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1334.
> fix latex completions with multiple cursors

- src/requests/init.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/1595.
> add ^ to completion triggers

- src/requests/textdocument.jl
We only have one crash report for this, but it seems very weird to me that we get a problem here at all.
> Add more info to an error msg

- src/requests/textdocument.jl
> parse entire file when checking is_parentof

- Project.toml
- src/document.jl
- src/languageserverinstance.jl
- src/requests/init.jl
- src/requests/textdocument.jl
Partner to https://github.com/julia-vscode/StaticLint.jl/pull/243. 
Allows incremental updating of the cst/semantic info without relying on updating the text incrementally (which I think we suspect is problematic).
> Incremental update for cst/semantic

- src/document.jl
This hopefully fixes a bug from crash reporting.
> Fix get_offset2 calculation

- src/requests/signatures.jl
Adds fallback method for get_signatures
Fixes Azure bug report.
> add fallback get_signatures method

- src/requests/workspace.jl
> remove VSCode special casing for workspace config request

- src/utilities.jl
> Fix a bug in remove_workspace_files

- src/requests/features.jl
Alternative to https://github.com/julia-vscode/LanguageServer.jl/pull/881. Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/681.
Haven't tried this with a non-VSCode client yet. Would also be nice to fine tune the `detail` and `selectionRange` fields a bit. It's also a bit odd that we list function parameters here (or at least different from e.g. TS).
> return DocumentSymbol instead of SymbolInformation

- src/requests/init.jl
Fixes https://github.com/julia-vscode/crashreporting-issues/issues/7.
> Fix a walkdir error handling case

- src/document.jl
- src/exception_types.jl
Helps with https://github.com/julia-vscode/crashreporting-issues/issues/8.
> Add a check for strings with NULL

- src/requests/actions.jl
Fixes https://github.com/julia-vscode/crashreporting-issues/issues/28
> fix reexport module action

- src/requests/hover.jl
> don't attach user code to error

- src/languageserverinstance.jl
- src/requests/init.jl
This makes our handling of shutdown/exit requests LSP-conformant.
Might help with https://github.com/julia-vscode/julia-vscode/issues/1951 (but I doubt it).
> improve shutdown request handling

- src/languageserverinstance.jl
- src/protocol/messagedefs.jl
- src/requests/features.jl
- src/requests/init.jl
Fixes #838 
Not clear how to trigger these on the client side so haven't tested
> selection ranges

- src/document.jl
- src/languageserverinstance.jl
- src/requests/actions.jl
- src/requests/completions.jl
- src/requests/features.jl
- src/requests/init.jl
- src/requests/textdocument.jl
- src/utilities.jl
- test/runtests.jl
> cosmetic tidying

- src/requests/init.jl
- src/requests/workspace.jl
> improve LSP conformance

- src/requests/textdocument.jl
Need to update the top-level span after adding trailing text.
> fix jmd toplevel span

- src/requests/completions.jl
Fixes https://github.com/fannheyward/coc-julia/issues/163#issuecomment-842214289.
> path completion range fix

- src/multienv.jl
> fix multienv bug

- src/requests/features.jl
Fixes https://github.com/julia-vscode/crashreporting-issues/issues/40.
> fix prepareRename_request

- src/requests/features.jl
Fixes https://github.com/julia-vscode/crashreporting-issues/issues/38
> fix selectionRange_request

- src/languageserverinstance.jl
For https://github.com/julia-vscode/SymbolServer.jl/pull/240.
> Improve SymbolServer progress reporting

- Project.toml
> Release 4.2.0

- src/requests/completions.jl
and improve qualify completions.
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/991.
> Fix import completions

- src/requests/init.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/1008.
> Fix ClientCapabilities.textDocument spec violation

- src/requests/completions.jl
- test/requests/completions.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2549
> Add emoji completions

- src/requests/features.jl
verbose, format_markdown & overwrite options are not filtered out from JuliaFormatter.toml because they only make sense for JuliaFormat functions to format a file not for formatting a text. Passing them makes format_text crash
Fixes #1027.
> Remove file format options to avoid JuliaFormatter crash

- README.md
- src/runserver.jl
Seems this is no longer needed.
https://github.com/julia-vscode/LanguageServer.jl/issues/750
> remove using SymbolServer from docs

- src/document.jl
- src/requests/completions.jl
- test/requests/completions.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/1034.
> Fix completions with multibyte chars in partial

- src/requests/completions.jl
- test/requests/completions.jl
This makes it easier to follow the code, no functional change.
> Use CompletionItemKinds named tuple instead of literals

- src/languageserverinstance.jl
This makes it easier to use Revise for reloading handler functions.
Requires Revise loaded in Main (before LanguageServer). Example:
```
using Revise
using LanguageServer
LanguageServer.USE_REVISE[] = true
```
> Enable reloading handler functions with Revise.

- src/requests/actions.jl
This adds action kinds to some of the supported actions. The ones left `missing` is not so clear what the kind should be, IMO. The spec seems to suggest you can invent your own things too though.
> Add code action kinds to some code actions.

- src/requests/textdocument.jl
- src/requests/workspace.jl
Fixes two issues from crash reporting.
> More TextDocument fixes

- src/requests/init.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/2969.
> Do not load docs with NULL in it from disc

- src/requests/features.jl
May fix a [crash report](https://portal.azure.com/#view/AppInsightsExtension/DetailsV2Blade/ComponentId~/%7B%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%2C%22Name%22%3A%22julia-vscode-insider%22%2C%22LinkedApplicationType%22%3A0%2C%22ResourceId%22%3A%22%252Fsubscriptions%252F6803c4ed-bcb4-41d4-bceb-7faf5e7a3469%252FresourceGroups%252FDefault%252Fproviders%252Fmicrosoft.insights%252Fcomponents%252Fjulia-vscode-insider%22%2C%22ResourceType%22%3A%22microsoft.insights%252Fcomponents%22%2C%22IsAzureFirst%22%3Afalse%7D/DataModel~/%7B%22eventId%22%3A%2299c8a8c3-f168-11ec-977a-9ffa20ed0611%22%2C%22timestamp%22%3A%222022-06-21T13%3A46%3A48.934Z%22%2C%22cacheId%22%3A%221214dfb8-20dc-4470-abb7-9d67f74f8c48%22%2C%22eventTable%22%3A%22exception …
> Fix a format selection text index error

- src/juliaworkspace.jl
@pfitzseb  I'm going to merge some of these right away, a bit tricky otherwise to keep things aligned. But I'll ping you on each of these so that you can review after the fact if you want to :)
> Extract a bit more semantic info from packages

- src/juliaworkspace.jl
- src/requests/init.jl
- src/requests/misc.jl
- test/test_juliaworkspace.jl
> Add more project semantics

- src/juliaworkspace.jl
- test/test_juliaworkspace.jl
Fixes a bug from crash reporting.
> Fix a JuliaWorkspace bug

- src/juliaworkspace.jl
- src/requests/init.jl
- src/requests/textdocument.jl
> Fix various test item detection bugs

- src/juliaworkspace.jl
- test/test_juliaworkspace.jl
> Fix a bug in the workspace functionality

- src/utilities.jl
> Vendor __convert_digit on old Julia versions

- Project.toml
- src/LanguageServer.jl
- src/extensions/extensions.jl
- src/requests/textdocument.jl
> Use TestItemDetection package

- Project.toml
- src/extensions/extensions.jl
- src/extensions/messagedefs.jl
- src/requests/textdocument.jl
> Progress on test item detection

- src/requests/signatures.jl
Trying to get to the bottom of a crash report with this.
> Add some diagnostic code for signature help

- src/requests/textdocument.jl
> Implement a test detection fix

- src/requests/textdocument.jl
Fixes https://github.com/julia-vscode/julia-vscode/issues/3274
@pfitzseb 
> warn if static analysis is slow for a given file

- README.md
Add instructions for Helix
Add information about other clients
Changes only the README.
> Add Helix, and others

- src/languageserverinstance.jl
- src/precompile.jl
- src/runserver.jl
- src/utilities.jl
> feat: add timer outputs

- src/requests/features.jl
- src/requests/hover.jl
Fixes https://github.com/julia-vscode/LanguageServer.jl/issues/1249.
> fix(docs): fix get_hover calls for docs

- Project.toml
> Bump min Julia version to 1.6

- src/requests/textdocument.jl
> Fix a testitem bug

- src/languageserverinstance.jl
- src/requests/init.jl
- src/requests/textdocument.jl
- src/requests/workspace.jl
- src/staticlint.jl
> Start outdated marking

- src/languageserverinstance.jl
There will be a corresponding extension PR that handles this.
> Send timing per request diagnostics

- Project.toml
- src/languageserverinstance.jl
- src/utilities.jl
- test/test_communication.jl
> Update to JSONRPC.jl v2
